name: 'titanic_features'
version: '1.0.0'

profile: 'titanic'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  titanic_features:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
